name: tiki_spam_cards
description: Spam Cards SDK for Tiki.
version: 0.0.9
homepage: https://mytiki.com
repository: https://github.com/tiki/spam_card
issue_tracker: https://github.com/tiki/spam_card/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  tiki_decision: ^0.0.10
  tiki_style: ^0.0.17
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4