name: spam_cards
description: Spam Cards SDK for Tiki.
version: 0.0.2
homepage: https://mytiki.com
repository: https://github.com/tiki/spam_cards
issue_tracker: https://github.com/tiki/spam_cards/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  decision: ^0.0.4
  google_provider: ^0.0.9
  microsoft_provider: ^0.0.8
  tiki_style: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4