name: spam_cards
description: Spam Cards SDK for Tiki.
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/spam_cards
issue_tracker: https://github.com/tiki/spam_cards/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  decision_sdk:
    path: ../decision_sdk
  google_provider:
    path: ../google_provider
  microsoft_provider:
    path: ../microsoft_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4